### PR TITLE
updating the configuration parsing and docs around it

### PR DESCRIPTION
**Pull request by choldgraf**

### CODE REVIEW

**Comment by choldgraf** [comment]
ping @najuzilu - I think that this will fix the configuration issues around the title etc...see the new config page here and please do provide feedback! https://beta.jupyterbook.org/use/customize.html

**Comment by najuzilu** [comment]
I added this to the config file
```
repository:
  url                       : https://executablebookproject.github.io/quantecon-example/source/getting_started.html
```
and got this error:
Screen Shot 2020-03-29 at 12 30 55 AM

**Comment by choldgraf** [comment]
Hmm, and you're on the latest master branch? Did you either reinstall with pip, or do a git pull?

**Comment by najuzilu** [comment]
Yes, I'm on the latest master branch. I ended up creating a new virtual env in conda just to make sure nothing funny was happening in the old one but the issue persists.

**Comment by choldgraf** [comment]
Gotcha - OK I *think* I know what's up, will try to get to it later today

**Comment by najuzilu** [comment]
@choldgraf I think we should also remove the word "documentation" from the title since it does not make sense if you're building a book. What do you think?

**Comment by choldgraf** [comment]
Can you upgrade your sphinx-book-theme repo and see if it works now?

Also, I agree about removing the word "documentation" in general, but I'm not sure where exactly you're talking about

**Comment by najuzilu** [comment]
> Can you upgrade your sphinx-book-theme repo and see if it works now?

I left a comment [here](https://github.com/ExecutableBookProject/sphinx-book-theme/pull/24).

> Also, I agree about removing the word "documentation" in general, but I'm not sure where exactly you're talking about

"documentation" is still showing up after the title and we should probably remove it:
Screen Shot 2020-03-30 at 12 31 15 AM

**Comment by choldgraf** [comment]
if the "documentation" word is still showing up, can you open an issue about it and include a link to the config of the book?

**Comment by najuzilu** [comment]
It is no longer showing. Thanks @choldgraf !

**Pull request merged**
