### PR TITLE
Updating book theme

### PR DESCRIPTION
**Pull request by choldgraf**
This updates the theme so that we use `sphinx-book-theme`

### CODE REVIEW

**Comment by choldgraf** [comment]
@rossbar pinging you since you just tried out the CLI. This PR makes the theme a more "book-like" theme (also, a separate repository now). There are still several bugs in the theme structure, but would love to know what you think about it!

**Comment by rossbar** [comment]
Thanks for the ping - just had a chance to look at it. The obvious downside is the page header clobbering the top of the content page, but as you said it's a WIP :). Generally I like the look, I think the content is more "front-and-center", which is important for a book theme.

**Comment by choldgraf** [comment]
@rossbar hmm, I'm not sure what you mean about the page header. Can you look at beta.jupyterbook.org for the latest?

**Comment by rossbar** [comment]
False alarm - the problem was I had installed a cached version in my virtualenv - I see the same output as <beta.jupyterbook.org> now when I make sure everything is upgraded appropriately.

**Pull request merged**
