### PR TITLE
reorganizing the docs

### PR DESCRIPTION
**Pull request by choldgraf**
This does a few things

* Changes `_toc.yml` so that `pages:` are now `sections:`. cc @najuzilu I think this will require an update on your end.
* Updates the documentation to give a better idea for how `header:` can be used to define chapters
* Reorganizes the docs a bit more in general to make them more modular.

### CODE REVIEW

**Comment by najuzilu** [comment]
@choldgraf fantastic! Is `divider` no longer supported? I'm just wondering because I did not see it in the documentation.

**Comment by choldgraf** [comment]
I did decide to drop divider support for now, because I think the same could be accomplished with header and css. What do you think?

**Comment by choldgraf** [comment]
(mostly because divider was doing a bunch of complicated stuff under the hood and it seems like there must be an easier way to accomplish it... We can always revisit though)

**Comment by najuzilu** [comment]
Sounds good!

**Pull request merged**
