### PR TITLE
adding functionality for cacheing and execution

### PR DESCRIPTION
**Pull request by choldgraf**
This brings in a few more features:

* the new MyST-NB cacheing/exec feature! It uses the config value `execute_notebooks`, and is set to "auto" by default.
* Improvements to the page layout documentation and some bugfixes in there

### CODE REVIEW

**Comment by najuzilu** [comment]
@choldgraf when do you think this PR will get merged?

**Comment by choldgraf** [comment]
once the tests pass - I will try to merge it within a day or so

**Comment by choldgraf** [comment]
OK I'm gonna give this a merge so that folks can play around with it!

@najuzilu make sure to update both your CLI and the sphinx-book-theme to get the latest changes!

**Comment by najuzilu** [comment]
I don't see any outputs being displayed (see [here](https://executablebookproject.github.io/quantecon-example/docs/python_by_example.html)). Also, would I expect to see outputs displayed on static pages? Just wondering if I need to publish the book every time to see if outputs are displayed or not.

**Comment by choldgraf** [comment]
Hmmm - it should execute automatically when you build the book. Make sure that you're setting `execute_notebooks = cache` in your config.yml file

**Comment by najuzilu** [comment]
I tried both `execute_notebooks  : auto` and `execute_notebooks : cache`. 
Do I also need to update my env with the latest MyST-NB?

**Comment by choldgraf** [comment]
definitely need the latest myst-nb. I know it's annoying, but a safe bet is to assume that before trying out any new features in the CLI, you should be running the latest version of both MyST-NB and sphinx-book-theme. Sometime soon things will slow down a bit, and then we can make proper releases with more predictable behavior

**Comment by najuzilu** [comment]
Thanks @choldgraf. It looks like for this to work, I can't just `pip install myst-nb` - which I did yesterday without thinking too much into it. Now that I have the latest, it's executing outputs...

**Comment by choldgraf** [comment]
Nope, all of this is very bleeding edge haha

**Pull request merged**
